find_package(TreelandProtocols REQUIRED)
find_package(PkgConfig REQUIRED)
pkg_check_modules(WAYLAND_CLIENT REQUIRED IMPORTED_TARGET wayland-client)
pkg_check_modules(XKBCOMMON REQUIRED IMPORTED_TARGET xkbcommon)

include(${CMAKE_CURRENT_SOURCE_DIR}/framework/ProtocolTest.cmake)

add_subdirectory(desktop-integration-fixture)
add_subdirectory(rendered-output-fixture)
add_subdirectory(treeland-app-id-resolver-v1)
add_subdirectory(treeland-capture-unstable-v1)
add_subdirectory(treeland-capture-desktop-v1)
add_subdirectory(treeland-dde-shell-v1)
add_subdirectory(treeland-dde-shell-desktop-v1)
add_subdirectory(treeland-ddm-v1)
add_subdirectory(treeland-foreign-toplevel-manager-v1)
add_subdirectory(treeland-output-manager-v1)
add_subdirectory(treeland-personalization-manager-v1)
add_subdirectory(treeland-personalization-desktop-v1)
add_subdirectory(treeland-prelaunch-splash-v2)
add_subdirectory(treeland-screensaver-v1)
add_subdirectory(treeland-screensaver-desktop-v1)
add_subdirectory(treeland-shortcut-manager-v2)
add_subdirectory(treeland-shortcut-manager-desktop-v2)
add_subdirectory(treeland-virtual-output-manager-v1)
add_subdirectory(treeland-virtual-output-desktop-v1)
add_subdirectory(treeland-wallpaper-color-v1)
add_subdirectory(treeland-wallpaper-manager-unstable-v1)
add_subdirectory(treeland-wallpaper-shell-unstable-v1)
add_subdirectory(treeland-wallpaper-desktop-v1)
add_subdirectory(treeland-window-management-v1)
add_subdirectory(treeland-window-management-desktop-v1)
