# SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only

get_property(treeland_protocol_test_targets GLOBAL
    PROPERTY TREELAND_PROTOCOL_TEST_TARGETS)
get_property(treeland_protocol_test_xmls GLOBAL
    PROPERTY TREELAND_PROTOCOL_TEST_XMLS)
set(treeland_protocol_test_xml_list
    "${CMAKE_CURRENT_BINARY_DIR}/protocol-test-xmls.txt")
file(WRITE "${treeland_protocol_test_xml_list}" "")
foreach(xml IN LISTS treeland_protocol_test_xmls)
    file(APPEND "${treeland_protocol_test_xml_list}" "${xml}\n")
endforeach()

file(GLOB_RECURSE treeland_protocol_build_files
    "${PROJECT_SOURCE_DIR}/src/CMakeLists.txt"
    "${PROJECT_SOURCE_DIR}/src/*/CMakeLists.txt"
    "${PROJECT_SOURCE_DIR}/src/*/*/CMakeLists.txt"
    "${PROJECT_SOURCE_DIR}/waylib/src/server/CMakeLists.txt")
set(treeland_served_protocol_xmls)
foreach(cmake_file IN LISTS treeland_protocol_build_files)
    file(READ "${cmake_file}" cmake_contents)
    string(REGEX MATCHALL "treeland-[A-Za-z0-9-]+\\.xml"
        protocol_xmls_in_file "${cmake_contents}")
    list(APPEND treeland_served_protocol_xmls ${protocol_xmls_in_file})
endforeach()
list(REMOVE_DUPLICATES treeland_served_protocol_xmls)
list(SORT treeland_served_protocol_xmls)
set(treeland_served_protocol_xml_list
    "${CMAKE_CURRENT_BINARY_DIR}/treeland-served-protocol-xmls.txt")
file(WRITE "${treeland_served_protocol_xml_list}" "")
foreach(xml IN LISTS treeland_served_protocol_xmls)
    file(APPEND "${treeland_served_protocol_xml_list}" "${xml}\n")
endforeach()

# CTest suppresses output from successful tests. Put the report in its
# post-test hook so a normal `ctest` invocation and CI log both show it.
set(treeland_protocol_coverage_post_command
    "\"${CMAKE_COMMAND}\""
    "\"-DPROTOCOL_TEST_XML_LIST=${treeland_protocol_test_xml_list}\""
    "\"-DTREELAND_SERVED_PROTOCOL_XML_LIST=${treeland_served_protocol_xml_list}\""
    "\"-DWAYLAND_PROTOCOLS_DATADIR=${WAYLAND_PROTOCOLS_DATADIR}\""
    "\"-DWLROOTS_PROTOCOL_DIR=${PROJECT_SOURCE_DIR}/3rdparty/wlroots/protocol\""
    "\"-DTREELAND_PROTOCOLS_DATA_DIR=${TREELAND_PROTOCOLS_DATA_DIR}\""
    -P
    "\"${CMAKE_CURRENT_LIST_DIR}/ProtocolTestCoverage.cmake\""
)
string(JOIN " " treeland_protocol_coverage_post_command
    ${treeland_protocol_coverage_post_command})
file(WRITE "${CMAKE_BINARY_DIR}/CTestCustom.cmake"
    "# Generated by tests/protocols/ProtocolTestCoverageTarget.cmake.\n"
    "list(APPEND CTEST_CUSTOM_POST_TEST\n"
    "    [==[${treeland_protocol_coverage_post_command}]==]\n"
    ")\n")

add_custom_target(protocol-test-coverage-target
    COMMAND "${CMAKE_CTEST_COMMAND}" --test-dir "${CMAKE_BINARY_DIR}" --output-on-failure -L protocols
    DEPENDS ${treeland_protocol_test_targets}
)
