# SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only

cmake_minimum_required(VERSION 3.25.0)

if(NOT DEFINED PROTOCOL_TEST_XML_LIST OR NOT DEFINED WAYLAND_PROTOCOLS_DATADIR
        OR NOT DEFINED WLROOTS_PROTOCOL_DIR OR NOT DEFINED TREELAND_PROTOCOLS_DATA_DIR
        OR NOT DEFINED TREELAND_SERVED_PROTOCOL_XML_LIST)
    message(FATAL_ERROR "ProtocolTestCoverage.cmake requires test XML list and protocol paths")
endif()

file(STRINGS "${PROTOCOL_TEST_XML_LIST}" tested_protocol_xmls)
set(tested_protocol_names)
foreach(xml IN LISTS tested_protocol_xmls)
    get_filename_component(protocol_name "${xml}" NAME_WE)
    list(APPEND tested_protocol_names "${protocol_name}")
endforeach()
list(REMOVE_DUPLICATES tested_protocol_names)
list(SORT tested_protocol_names)

function(collect_protocol_names protocol_dir output_variable)
    file(GLOB_RECURSE protocol_xmls LIST_DIRECTORIES FALSE "${protocol_dir}/*.xml")
    set(protocol_names)
    foreach(xml IN LISTS protocol_xmls)
        get_filename_component(protocol_name "${xml}" NAME_WE)
        list(APPEND protocol_names "${protocol_name}")
    endforeach()
    list(REMOVE_DUPLICATES protocol_names)
    list(SORT protocol_names)
    set(${output_variable} "${protocol_names}" PARENT_SCOPE)
endfunction()

function(pad_right text width output_variable)
    string(LENGTH "${text}" text_length)
    math(EXPR padding "${width} - ${text_length}")
    if(padding GREATER 0)
        string(REPEAT " " ${padding} spaces)
    else()
        set(spaces "")
    endif()
    set(${output_variable} "${text}${spaces}" PARENT_SCOPE)
endfunction()

function(report_coverage source_name protocol_names)
    set(registered_names)
    set(unregistered_names)
    foreach(protocol_name IN LISTS protocol_names)
        if(protocol_name IN_LIST tested_protocol_names)
            list(APPEND registered_names "${protocol_name}")
        else()
            list(APPEND unregistered_names "${protocol_name}")
        endif()
    endforeach()

    list(LENGTH registered_names protocol_count)
    list(LENGTH registered_names covered_count)
    if(protocol_count GREATER 0)
        math(EXPR coverage_tenths "${covered_count} * 1000 / ${protocol_count}")
        math(EXPR coverage_whole "${coverage_tenths} / 10")
        math(EXPR coverage_fraction "${coverage_tenths} % 10")
    else()
        set(coverage_whole 0)
        set(coverage_fraction 0)
    endif()

    set(coverage_count "${covered_count} / ${protocol_count}")
    set(coverage_percent "${coverage_whole}.${coverage_fraction}%")
    pad_right("${source_name}" 36 coverage_source_column)
    pad_right("${coverage_count}" 10 coverage_count_column)
    pad_right("${coverage_percent}" 8 coverage_percent_column)
    message(STATUS "| ${coverage_source_column} | ${coverage_count_column} | ${coverage_percent_column} |")
    if(unregistered_names)
        set(coverage_unregistered_protocols "${unregistered_names}" PARENT_SCOPE)
    else()
        set(coverage_unregistered_protocols "" PARENT_SCOPE)
    endif()

    set(coverage_protocol_count "${protocol_count}" PARENT_SCOPE)
    set(coverage_covered_count "${covered_count}" PARENT_SCOPE)
endfunction()

function(report_unregistered_xmls source_name protocol_names)
    if(NOT protocol_names)
        return()
    endif()

    list(LENGTH protocol_names protocol_count)
    message(STATUS "  ${source_name} (${protocol_count}):")
    set(line "    ")
    foreach(protocol_name IN LISTS protocol_names)
        if(line STREQUAL "    ")
            set(candidate "${line}${protocol_name}")
        else()
            set(candidate "${line}, ${protocol_name}")
        endif()
        string(LENGTH "${candidate}" candidate_length)
        if(candidate_length GREATER 100)
            message(STATUS "${line}")
            set(line "    ${protocol_name}")
        else()
            set(line "${candidate}")
        endif()
    endforeach()
    message(STATUS "${line}")
endfunction()

collect_protocol_names("${WAYLAND_PROTOCOLS_DATADIR}" wayland_protocol_names)
collect_protocol_names("${WLROOTS_PROTOCOL_DIR}" wlroots_protocol_names)
collect_protocol_names("${TREELAND_PROTOCOLS_DATA_DIR}" treeland_protocol_names)
file(STRINGS "${TREELAND_SERVED_PROTOCOL_XML_LIST}" treeland_served_protocol_xmls)
set(treeland_served_protocol_names)
foreach(xml IN LISTS treeland_served_protocol_xmls)
    get_filename_component(protocol_name "${xml}" NAME_WE)
    list(APPEND treeland_served_protocol_names "${protocol_name}")
endforeach()
list(REMOVE_DUPLICATES treeland_served_protocol_names)
list(SORT treeland_served_protocol_names)

message(STATUS "")
message(STATUS "Protocol XML test coverage")
message(STATUS "Only XMLs referenced by registered protocol tests are counted.")
message(STATUS "+--------------------------------------+------------+----------+")
message(STATUS "| Scope                                | Test XMLs  | Coverage |")
message(STATUS "+--------------------------------------+------------+----------+")
report_coverage("wayland-protocols" "${wayland_protocol_names}")
set(wayland_unregistered_protocols "${coverage_unregistered_protocols}")
report_coverage("wlroots" "${wlroots_protocol_names}")
set(wlroots_unregistered_protocols "${coverage_unregistered_protocols}")
report_coverage("Treeland built-in service protocols" "${treeland_served_protocol_names}")
message(STATUS "+--------------------------------------+------------+----------+")
list(LENGTH treeland_protocol_names treeland_protocol_inventory_count)
message(STATUS "Treeland private XML inventory: ${treeland_protocol_inventory_count} (informational; not counted)")

message(STATUS "")
message(STATUS "Available XMLs without a registered protocol test (not counted):")
report_unregistered_xmls("wayland-protocols" "${wayland_unregistered_protocols}")
report_unregistered_xmls("wlroots" "${wlroots_unregistered_protocols}")

message(STATUS "")
message(STATUS "Protocol coverage report complete.")
cmake_language(EXIT 0)
